#!/usr/bin/env python3
"""P1: merge GATK public CLI options into the native registry and C++ catalog.

Cloud/Spark options stay deferred (fail-closed, not Java).  Picard-wrapped
tools keep their existing registry surface.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(Path(__file__).resolve().parent))
import inventory_cli_coverage as inventory  # noqa: E402

REGISTRY = inventory.REGISTRY
CATALOG = ROOT / "fastgatk-native/include/fastgatk/cli/gatk_cli_catalog.hpp"


def _extend(entry: dict, key: str, names: list[str]) -> int:
    current = [str(x) for x in entry.get(key, [])]
    seen = set(current)
    added = 0
    for name in names:
        if name not in seen:
            current.append(name)
            seen.add(name)
            added += 1
    entry[key] = current
    return added


def merge_registry(registry: dict, coverage: dict) -> dict[str, int]:
    stats = {"tools": 0, "flags": 0, "values": 0}
    for tool, bucket in coverage["tools"].items():
        entry = registry["tools"][tool]
        native = inventory.registry_options(entry)
        flags = set(bucket.get("gatk_flags", []))
        added_flags: list[str] = []
        added_values: list[str] = []
        for opt in bucket.get("must-implement", []):
            if opt in native:
                continue
            if opt in flags:
                added_flags.append(opt)
            else:
                added_values.append(opt)
        stats["flags"] += _extend(entry, "flag_options", added_flags)
        stats["flags"] += _extend(entry, "optional_boolean_options", added_flags)
        # Dispatcher optional booleans must also be flags; listing them as
        # value_options matches existing GATK Boolean-as-value spellings.
        stats["values"] += _extend(entry, "value_options", added_flags + added_values)
        stats["tools"] += 1
    return stats


def write_catalog(registry: dict) -> None:
    lines = [
        "#pragma once",
        "// Generated by apply_p1_cli_coverage.py.  Do not edit by hand.",
        "#include <string>",
        "#include <string_view>",
        "#include <unordered_map>",
        "#include <unordered_set>",
        "",
        "namespace fastgatk::cli {",
        "",
        "struct OptionSets {",
        "    std::unordered_set<std::string> flags;",
        "    std::unordered_set<std::string> values;",
        "};",
        "",
        "inline const OptionSets& options_for(std::string_view tool) {",
        "    static const std::unordered_map<std::string, OptionSets> kCatalog = {",
    ]
    for tool, entry in registry["tools"].items():
        flags = sorted({str(x) for x in entry.get("flag_options", [])})
        values = sorted({str(x) for x in entry.get("value_options", [])} - set(flags))
        def cpp_set(names: list[str]) -> str:
            inner = ", ".join(json.dumps(n) for n in names)
            return "{" + inner + "}"
        lines.append(
            f'        {{"{tool}", {{{cpp_set(flags)}, {cpp_set(values)}}}}},'
        )
    lines += [
        "    };",
        "    static const OptionSets kEmpty{};",
        "    const auto found = kCatalog.find(std::string(tool));",
        "    return found == kCatalog.end() ? kEmpty : found->second;",
        "}",
        "",
        "}  // namespace fastgatk::cli",
        "",
    ]
    CATALOG.parent.mkdir(parents=True, exist_ok=True)
    CATALOG.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    inventory.main()
    coverage = json.loads(inventory.OUT.read_text(encoding="utf-8"))
    registry = json.loads(REGISTRY.read_text(encoding="utf-8"))
    stats = merge_registry(registry, coverage)
    REGISTRY.write_text(json.dumps(registry, indent=2) + "\n", encoding="utf-8")
    write_catalog(registry)
    inventory.main()
    coverage = json.loads(inventory.OUT.read_text(encoding="utf-8"))
    print(json.dumps({
        "status": "pass",
        "merged": stats,
        "catalog": str(CATALOG),
        "must-implement": coverage["summary"].get("must-implement", 0),
        "tools-with-gaps": coverage["summary"].get("tools-with-gaps", 0),
        "deferred-cloud-or-spark": coverage["summary"].get("deferred-cloud-or-spark", 0),
    }, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
