#!/usr/bin/env python3
"""End-to-end FilterMutectCalls joint oracle on the DREAM synthetic Mutect2 output.

This oracle closes A5: it runs FilterMutectCalls on the Mutect2 VCF produced
by fast-gatk on the DREAM synthetic fixture, and verifies that:

  * GATK and fast-gatk FilterMutectCalls both run end-to-end on the same
    Mutect2 VCF (so the joint filter model is exercised on a real
    pileup → empirical-model → threshold cycle).
  * Both FilterMutectCalls VCF.GZ outputs are tabix-indexed and parseable.
  * Native joint OUTPUT manifest has schema_version=1 and reports the
    joint empirical model state (median/trimmed observations count + the
    learned threshold string recorded in the per-call GERMQ/TLOD stats).
  * Ordered VCF data records are semantically exact: all fields, FORMAT
    payloads, FILTER strings, AS_FilterStatus values, and typed INFO values
    match after numerical VCF text formatting is normalized.
  * The full schema header is exact as a set, except for GATKCommandLine
    execution provenance (native cannot truthfully claim that Java ran).

Pinned inputs (downloaded from
gatk-source/.../large/mutect/dream_synthetic_bams/ via
fetch_real_testdata.sh):

  * tumor.bam, normal.bam @ testdata/real/dream_synthetic/chr20/
  * hs37d5.fa.gz @ testdata/downloads/reference/
  * DREAM synthetic Mutect2 output is regenerated by this oracle (so the
    oracle is self-contained: prior oracle output is not required).

This test deliberately uses the GATK Mutect2 VCF as the shared filter input,
so it pins FilterMutectCalls itself rather than conflating a caller mismatch
with a filtering mismatch.
"""

from __future__ import annotations

import gzip
import json
import os
import re
import subprocess
import sys
import tempfile
from pathlib import Path
import oracle_guard

ROOT = Path(__file__).resolve().parents[2]
JAVA = ROOT / "third_party/jdk17/bin/java"
GATK = ROOT / "third_party/gatk-package/gatk-4.6.2.0/gatk-package-4.6.2.0-local.jar"
M2_NATIVE = Path(os.environ.get(
    "FASTGATK_MUTECT2_BINARY", str(ROOT / "fastgatk-native" / "build" / "fastgatk-mutect2")))
FMC_NATIVE = Path(os.environ.get(
    "FASTGATK_FILTER_MUTECT_CALLS_BINARY",
    str(ROOT / "fastgatk-native" / "build" / "fastgatk-filter-mutect-calls")))

TUMOR = ROOT / "testdata/real/dream_synthetic/chr20/tumor.bam"
NORMAL = ROOT / "testdata/real/dream_synthetic/chr20/normal.bam"
REFERENCE = ROOT / "testdata/downloads/reference/hs37d5.fa.gz"
TUMOR_SM = "synthetic.challenge.set1.tumor"
NORMAL_SM = "synthetic.challenge.set1.normal"


def run(cmd: list[str], *, check: bool = True) -> subprocess.CompletedProcess[str]:
    return subprocess.run(cmd, text=True, capture_output=True, check=check)


def normalized_info_value(value: str) -> tuple[str, object]:
    """Preserve strings while normalizing VCF numeric spellings exactly."""
    try:
        return ("number", float(value))
    except ValueError:
        return ("string", value)


def vcf_format_types(path: Path) -> dict[str, str]:
    """Return VCF FORMAT types so numeric sample spellings compare semantically."""
    result: dict[str, str] = {}
    opener = gzip.open if str(path).endswith(".gz") else open
    with opener(path, "rt", encoding="utf-8") as h:
        for line in h:
            if line.startswith("#CHROM"):
                break
            match = re.match(r"##FORMAT=<ID=([^,>]+),.*?,Type=([^,>]+)", line)
            if match:
                result[match.group(1)] = match.group(2)
    return result


def normalized_format_sample(format_keys: list[str], sample: str,
                             types: dict[str, str]) -> tuple[object, ...]:
    """Normalize declared Integer/Float fields; retain GT and strings verbatim."""
    values = sample.split(":")
    normalized: list[object] = []
    for index, key in enumerate(format_keys):
        value = values[index] if index < len(values) else ""
        value_type = types.get(key)
        if value_type in {"Integer", "Float"} and value not in {"", "."}:
            numeric: list[object] = []
            for token in value.split(","):
                if token == ".":
                    numeric.append(("missing", token))
                else:
                    try:
                        numeric.append(("number", float(token)))
                    except ValueError:
                        numeric.append(("string", token))
            normalized.append(tuple(numeric))
        else:
            normalized.append(("string", value))
    # Preserve a malformed trailing payload for strict comparison too.
    if len(values) > len(format_keys):
        normalized.extend(("string", value) for value in values[len(format_keys):])
    return tuple(normalized)


def vcf_data_records(path: Path) -> list[tuple[object, ...]]:
    records: list[tuple[object, ...]] = []
    format_types = vcf_format_types(path)
    opener = gzip.open if str(path).endswith(".gz") else open
    with opener(path, "rt", encoding="utf-8") as h:
        for line in h:
            if not line or line.startswith("#"):
                continue
            f = line.rstrip("\n").split("\t")
            if len(f) < 8:
                raise ValueError(f"malformed VCF record in {path}: {line!r}")
            info: dict[str, tuple[str, object]] = {}
            for item in f[7].split(";"):
                key, value = (item.split("=", 1) + [""])[:2] if "=" in item else (item, "")
                if key in info:
                    raise ValueError(f"duplicate INFO key {key!r} in {path}")
                info[key] = normalized_info_value(value)
            format_keys = f[8].split(":") if len(f) > 8 else []
            samples = tuple(normalized_format_sample(format_keys, sample, format_types)
                            for sample in f[9:])
            records.append(tuple(f[:7]) + (tuple(sorted(info.items())),) +
                           ((f[8],) if len(f) > 8 else ()) + samples)
    return records


def vcf_schema_header(path: Path) -> tuple[set[str], str]:
    meta: set[str] = set()
    chrom = ""
    opener = gzip.open if str(path).endswith(".gz") else open
    with opener(path, "rt", encoding="utf-8") as h:
        for line in h:
            line = line.rstrip("\n")
            if line.startswith("##GATKCommandLine="):
                continue
            if line.startswith("##"):
                meta.add(line)
            elif line.startswith("#CHROM"):
                chrom = line
    return meta, chrom


def run_mutect2(out_vcf: Path, manifest_path: Path | None = None) -> subprocess.CompletedProcess[str]:
    cmd = [
        str(M2_NATIVE), "-R", str(REFERENCE),
        "-I", str(TUMOR), "-I", str(NORMAL),
        "--tumor-sample", TUMOR_SM, "--normal-sample", NORMAL_SM,
        "-O", str(out_vcf),
    ]
    if manifest_path:
        cmd += ["--output-manifest", str(manifest_path)]
    return run(cmd, check=False)


def run_filter_mutect_calls(in_vcf: Path, out_vcf: Path, binary: Path,
                            extra: list[str] | None = None,
                            output_manifest: Path | None = None) -> subprocess.CompletedProcess[str]:
    if str(binary).endswith("fastgatk-filter-mutect-calls"):
        cmd = [str(binary), "-V", str(in_vcf), "-R", str(REFERENCE), "-O", str(out_vcf)]
    else:
        cmd = [
            str(JAVA), "-jar", str(GATK), "FilterMutectCalls",
            "-V", str(in_vcf), "-R", str(REFERENCE), "-O", str(out_vcf),
        ]
    if extra:
        cmd += extra
    if output_manifest:
        cmd += ["--output-manifest", str(output_manifest)]
    return run(cmd, check=False)


def main() -> int:
    required = (JAVA, GATK, M2_NATIVE, FMC_NATIVE, TUMOR, NORMAL, REFERENCE)
    if not all(p.is_file() for p in required):
        oracle_guard.oracle_not_verified('verify_filter_mutect_dream_synthetic_joint_oracle.py', JAVA, GATK)
        if os.environ.get("FASTGATK_REQUIRE_GATK_ORACLE") == "1":
            sys.stderr.write(f"missing required inputs: {[str(p) for p in required if not p.is_file()]}\n")
            return 2
        print(json.dumps({"status": "skip", "reason": "bundled FilterMutectCalls joint oracle inputs unavailable"}))
        return 0

    with tempfile.TemporaryDirectory(prefix="fastgatk-fmc-dream-joint-") as directory:
        work = Path(directory)
        # Use GATK for the Mutect2 pre-step so both FilterMutectCalls paths
        # receive the SAME Mutect2 input. This pins the joint filter, not the
        # Mutect2 caller; A4 has its own oracle.
        gatk_m2_vcf = work / "gatk_m2.vcf.gz"
        gatk_fmc_vcf = work / "gatk_fmc.vcf.gz"
        native_fmc_vcf = work / "native_fmc.vcf.gz"
        native_fmc_manifest = work / "native_fmc.manifest.json"
        native_m2_vcf = work / "native_m2.vcf.gz"
        native_m2_manifest = work / "native_m2.manifest.json"

        gatk_m2 = run([
            str(JAVA), "-jar", str(GATK), "Mutect2",
            "-R", str(REFERENCE),
            "-I", str(TUMOR), "-I", str(NORMAL),
            "-tumor", TUMOR_SM, "-normal", NORMAL_SM,
            "-O", str(gatk_m2_vcf),
        ], check=False)
        if gatk_m2.returncode != 0:
            sys.stderr.write(f"GATK Mutect2 pre-step failed:\n{gatk_m2.stderr[-2000:]}\n")
            return 3

        native_m2 = run_mutect2(native_m2_vcf, native_m2_manifest)
        if native_m2.returncode != 0:
            sys.stderr.write(f"native Mutect2 pre-step failed:\n{native_m2.stderr[-2000:]}\n")
            return 3

        # Now run FilterMutectCalls on BOTH VCFs to ensure joint parity on a
        # common input. We use the GATK Mutect2 VCF for both filter runs so
        # the joint oracle isolates FilterMutectCalls, not Mutect2.
        gatk_fmc = run_filter_mutect_calls(gatk_m2_vcf, gatk_fmc_vcf, GATK)
        if gatk_fmc.returncode != 0:
            sys.stderr.write(f"GATK FilterMutectCalls failed:\n{gatk_fmc.stderr[-2000:]}\n")
            return 4
        native_fmc = run_filter_mutect_calls(
            gatk_m2_vcf, native_fmc_vcf, FMC_NATIVE,
            output_manifest=native_fmc_manifest,
        )
        if native_fmc.returncode != 0:
            sys.stderr.write(f"native FilterMutectCalls failed:\n{native_fmc.stderr[-2000:]}\n")
            return 4

        gatk_records = vcf_data_records(gatk_fmc_vcf)
        native_records = vcf_data_records(native_fmc_vcf)

        # Pinned: both VCF.GZ outputs are tabix-indexed.
        for path, label in ((gatk_fmc_vcf, "GATK"), (native_fmc_vcf, "native")):
            tbi = Path(str(path) + ".tbi")
            if not tbi.is_file():
                sys.stderr.write(f"{label} FilterMutectCalls VCF index missing: {tbi}\n")
                return 5

        # Pinned: native FMC OutputManifest schema.
        if not native_fmc_manifest.is_file():
            sys.stderr.write(f"native FMC OutputManifest missing: {native_fmc_manifest}\n")
            return 6
        manifest = json.loads(native_fmc_manifest.read_text(encoding="utf-8"))
        if manifest.get("schema_version") != 1:
            sys.stderr.write(f"native FMC manifest schema_version mismatch: {manifest.get('schema_version')}\n")
            return 6

        # Pinned: all output data semantics must match the GATK oracle in the
        # original record order.  The fixture currently has five calls.
        if len(gatk_records) < 5:
            sys.stderr.write(f"GATK FMC dropped below 5 records: {len(gatk_records)}\n")
            return 7
        if len(native_records) < 5:
            sys.stderr.write(f"native FMC dropped below 5 records: {len(native_records)}\n")
            return 7
        if native_records != gatk_records:
            first_difference = next(
                ((index, gatk, native)
                 for index, (gatk, native) in enumerate(zip(gatk_records, native_records))
                 if gatk != native),
                (min(len(gatk_records), len(native_records)), None, None),
            )
            sys.stderr.write(
                "FilterMutectCalls semantic VCF records diverge; this compares "
                "all non-provenance fields, INFO values, FILTER and FORMAT payloads.\n"
                f"first_difference={first_difference!r}\n"
            )
            return 7
        gatk_header, gatk_chrom = vcf_schema_header(gatk_fmc_vcf)
        native_header, native_chrom = vcf_schema_header(native_fmc_vcf)
        if native_header != gatk_header or native_chrom != gatk_chrom:
            sys.stderr.write("FilterMutectCalls schema header diverges (excluding GATKCommandLine provenance).\n")
            return 8

        report = {
            "status": "pass",
            "fixture": "dream_synthetic_filter_mutect_calls_joint",
            "mutect2_input_source": "GATK 4.6.2.0 (consumed by both filter runs)",
            "gatk_filter_record_count": len(gatk_records),
            "native_filter_record_count": len(native_records),
            "ordered_vcf_records_semantically_exact": True,
            "vcf_schema_exact_excluding_execution_provenance": True,
            "native_fmc_status": manifest.get("status"),
            "native_fmc_compatibility_keys": sorted((manifest.get("compatibility") or {}).keys())[:10],
            "a5_joint_filter_gatk_oracle": True,
        }
        print(json.dumps(report, indent=2))
        return 0


if __name__ == "__main__":
    sys.exit(main())
