#!/usr/bin/env python3
"""Funcotator oracle: VCF output over gencode + simpleXSV data sources.

Runs GATK 4.6.2.0's Funcotator and the native fastgatk-funcotator on
identical self-contained fixtures and requires byte-identical output
(headers aside from execution provenance — `##Funcotator Version` /
`##GATKCommandLine` / `##fileDate` — data rows verbatim), matching the
without_provenance convention of the other GATK contract oracles.

Covered semantics (Funcotator.java / FuncotatorEngine.java /
DataSourceUtils.java / VcfOutputRenderer.java):
  1. simpleXSV GENE_NAME hit and miss: the xsv fields fill per selected
     transcript and come back empty on the no-transcript (IGR) block.
  2. transcript multi-block assembly: `--transcript-selection-mode ALL`
     yields `[...]#[...]` blocks joined per ALT, fields joined by `|`.
  3. `--annotation-default NAME:value` appends the default as the last
     field of every block.

Fixtures are generated by this script (the gatk-source "large" funcotator
fixtures are unmaterialized git-lfs pointers in this checkout): a 600bp
mini reference, a two-transcript gencode data source (GTF + transcript
FASTA with fai/dict), and a two-row simpleXSV table.  The GTF tribble
index is built with the bundled IndexFeatureFile.
"""
from __future__ import annotations

import json
import os
import subprocess
import sys
import tempfile
from pathlib import Path

import oracle_guard


ROOT = Path(__file__).resolve().parents[2]
JAVA = ROOT / "third_party/jdk17/bin/java"
GATK = ROOT / "third_party/gatk-package/gatk-4.6.2.0/gatk-package-4.6.2.0-local.jar"
NATIVE = Path(os.environ.get(
    "FASTGATK_FUNCOTATOR_BINARY",
    str(ROOT / "fastgatk-native/build/fastgatk-funcotator")))

GTF = """\
chrMini\thavana\tgene\t100\t329\t.\t+\t.\tgene_id "ENSGMINI0001"; gene_name "MINIGENE"; gene_type "protein_coding"; level "2";
chrMini\thavana\ttranscript\t100\t329\t.\t+\t.\tgene_id "ENSGMINI0001"; transcript_id "ENSTMINI0001"; gene_name "MINIGENE"; gene_type "protein_coding"; level "2"; transcript_type "protein_coding"; tag "basic"; tag "appris_principal_1";
chrMini\thavana\texon\t100\t159\t.\t+\t.\tgene_id "ENSGMINI0001"; transcript_id "ENSTMINI0001"; gene_name "MINIGENE"; exon_number "1"; exon_id "ENSEXMINI0001"; level "2";
chrMini\thavana\tCDS\t100\t159\t.\t+\t0\tgene_id "ENSGMINI0001"; transcript_id "ENSTMINI0001"; gene_name "MINIGENE"; exon_number "1"; level "2"; protein_id "ENSPMINI0001";
chrMini\thavana\texon\t250\t329\t.\t+\t.\tgene_id "ENSGMINI0001"; transcript_id "ENSTMINI0001"; gene_name "MINIGENE"; exon_number "2"; exon_id "ENSEXMINI0002"; level "2";
chrMini\thavana\tCDS\t250\t329\t.\t+\t0\tgene_id "ENSGMINI0001"; transcript_id "ENSTMINI0001"; gene_name "MINIGENE"; exon_number "2"; level "2"; protein_id "ENSPMINI0001";
chrMini\thavana\ttranscript\t100\t159\t.\t+\t.\tgene_id "ENSGMINI0001"; transcript_id "ENSTMINI0002"; gene_name "MINIGENE"; gene_type "protein_coding"; level "2"; transcript_type "protein_coding"; tag "basic";
chrMini\thavana\texon\t100\t159\t.\t+\t.\tgene_id "ENSGMINI0001"; transcript_id "ENSTMINI0002"; gene_name "MINIGENE"; exon_number "1"; exon_id "ENSEXMINI0003"; level "2";
chrMini\thavana\tCDS\t100\t159\t.\t+\t0\tgene_id "ENSGMINI0001"; transcript_id "ENSTMINI0002"; gene_name "MINIGENE"; exon_number "1"; level "2"; protein_id "ENSPMINI0002";
"""

GENCODE_CONFIG = """\
name = Gencode
version = Mini
src_file = mini.gtf
origin_location = testdata
preprocessing_script = none
ncbi_build_version = 37
type = gencode
gencode_fasta_path = mini.tx.fa
"""

XSV_CONFIG = """\
name = xsv_mini
version = 1
src_file = mini.tsv
origin_location = testdata
preprocessing_script = none
type = simpleXSV
xsv_delimiter = \\t
xsv_key = GENE_NAME
xsv_key_column = 0
xsv_permissive_cols = false
"""

XSV_TABLE = "GENE_NAME\tSCORE\tFLAG\nMINIGENE\t42\tYES\nOTHERGENE\t7\tNO\n"

CASES = [
    ("canonical", []),
    ("all-transcripts-defaults",
     ["--transcript-selection-mode", "ALL",
      "--annotation-default", "MY_DEFAULT:hello"]),
]


def without_provenance(path: Path) -> list[str]:
    with open(path, encoding="utf-8") as handle:
        return [line.rstrip("\n") for line in handle
                if not line.startswith(("##Funcotator Version=",
                                        "##GATKCommandLine=", "##fileDate="))]


def run(command: list[str], timeout: int = 600) -> subprocess.CompletedProcess[str]:
    return subprocess.run(command, capture_output=True, text=True, check=False,
                          timeout=timeout)


def write_fixtures(work: Path) -> None:
    import random
    random.seed(7)
    bases = "".join(random.choice("ACGT") for _ in range(600))
    reference_header = ">chrMini\n"
    (work / "mini.fa").write_text(
        reference_header + "\n".join(bases[i:i + 60] for i in range(0, 600, 60)) + "\n")
    (work / "mini.fa.fai").write_text(
        f"chrMini\t600\t{len(reference_header)}\t60\t61\n")
    (work / "mini.dict").write_text(
        "@HD\tVN:1.6\n@SQ\tSN:chrMini\tLN:600\tM5:" + "0" * 32 + "\n")

    gencode = work / "DS/gencode_mini/hg19"
    gencode.mkdir(parents=True)
    tx1 = bases[99:159] + bases[249:329]
    tx2 = bases[99:159]
    records = [
        (">ENSTMINI0001|ENSGMINI0001|OTTHUMG0001|OTTHUMT0001|MINIGENE-201|MINIGENE|140|protein_coding|", tx1),
        (">ENSTMINI0002|ENSGMINI0001|OTTHUMG0001|OTTHUMT0002|MINIGENE-202|MINIGENE|60|protein_coding|", tx2),
    ]
    fasta_lines = []
    for name, sequence in records:
        fasta_lines.append(name)
        for index in range(0, len(sequence), 60):
            fasta_lines.append(sequence[index:index + 60])
    (gencode / "mini.tx.fa").write_text("\n".join(fasta_lines) + "\n")
    # Build the fai from the written bytes so the offsets cannot drift.
    fai_rows = []
    offset = 0
    current = None
    for line in (gencode / "mini.tx.fa").read_bytes().split(b"\n"):
        if line.startswith(b">"):
            if current is not None:
                fai_rows.append(current)
            current = [line[1:].split(b"|")[0].decode(), 0, offset + len(line) + 1, 60, 61]
        elif line and current is not None:
            current[1] += len(line)
        offset += len(line) + 1
    if current is not None:
        fai_rows.append(current)
    (gencode / "mini.tx.fa.fai").write_text(
        "\n".join("\t".join(map(str, row)) for row in fai_rows) + "\n")
    (gencode / "mini.tx.dict").write_text(
        "@HD\tVN:1.6\n" + "".join(f"@SQ\tSN:{row[0]}\tLN:{row[1]}\n" for row in fai_rows))
    (gencode / "mini.gtf").write_text(GTF)
    (gencode / "gencode.config").write_text(GENCODE_CONFIG)

    xsv = work / "DS/xsv_mini/hg19"
    xsv.mkdir(parents=True)
    (xsv / "xsv.config").write_text(XSV_CONFIG)
    (xsv / "mini.tsv").write_text(XSV_TABLE)

    def variant(position: int) -> str:
        reference = bases[position - 1]
        alternate = "ACGT"[("ACGT".index(reference) + 1) % 4]
        return f"chrMini\t{position}\t.\t{reference}\t{alternate}\t.\t.\t.\tGT\t0/1"

    (work / "input.vcf").write_text(
        "##fileformat=VCFv4.2\n"
        "##contig=<ID=chrMini,length=600>\n"
        '##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">\n'
        "#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tS1\n"
        + "\n".join(variant(position) for position in (120, 280, 500)) + "\n")


def main() -> int:
    if not all(path.is_file() for path in (JAVA, GATK, NATIVE)):
        oracle_guard.oracle_not_verified(
            'verify_funcotator_vcf_gatk_oracle.py', JAVA, GATK)
        if os.environ.get("FASTGATK_REQUIRE_GATK_ORACLE") == "1":
            raise SystemExit("bundled GATK Funcotator inputs are required")
        print(json.dumps({"status": "skip",
                          "reason": "bundled GATK or native Funcotator unavailable"}))
        return 0

    results = []
    with tempfile.TemporaryDirectory(prefix="fastgatk-funcotator-") as directory:
        work = Path(directory)
        write_fixtures(work)
        index = run([str(JAVA), "-Xmx512m", "-jar", str(GATK), "IndexFeatureFile",
                     "-I", str(work / "DS/gencode_mini/hg19/mini.gtf")])
        if index.returncode != 0:
            print(json.dumps({"status": "fail", "stage": "index",
                              "stderr": index.stderr[-2000:]}))
            return 1

        for name, extra in CASES:
            gatk_output = work / f"gatk.{name}.vcf"
            native_output = work / f"native.{name}.vcf"
            common = ["-V", str(work / "input.vcf"), "-R", str(work / "mini.fa"),
                      "--ref-version", "hg19", "--data-sources-path", str(work / "DS"),
                      "--output-file-format", "VCF", *extra]
            gatk = run([str(JAVA), "-Xmx512m", "-jar", str(GATK), "Funcotator",
                        "-O", str(gatk_output), *common])
            if gatk.returncode != 0:
                print(json.dumps({"status": "fail", "stage": f"gatk:{name}",
                                  "stderr": gatk.stderr[-2000:]}))
                return 1
            native = run([str(NATIVE), "-O", str(native_output), *common])
            if native.returncode != 0:
                print(json.dumps({"status": "fail", "stage": f"native:{name}",
                                  "stderr": native.stderr[-2000:]}))
                return 1
            expected = without_provenance(gatk_output)
            observed = without_provenance(native_output)
            mismatches = [
                {"line": index, "gatk": line, "native": observed[index]
                    if index < len(observed) else None}
                for index, line in enumerate(expected)
                if index >= len(observed) or observed[index] != line
            ]
            results.append({"case": name,
                            "status": "pass" if not mismatches and
                                len(observed) == len(expected) else "fail",
                            "mismatches": mismatches})

    payload = {
        "status": "pass" if all(item["status"] == "pass" for item in results)
                  else "fail",
        "cases": results,
        "oracle": "GATK-4.6.2.0",
        "covered": ["xsv-gene-name-hit-miss", "transcript-multi-block",
                    "annotation-default"],
    }
    print(json.dumps(payload, sort_keys=True))
    return 0 if payload["status"] == "pass" else 1


if __name__ == "__main__":
    raise SystemExit(main())
